<?php

function query_entities() {
  $current_mid = arg(1);
  $current_mid = (int)$current_mid;

  $query = db_select('micro', 'm')
  ->fields('m', array('mid', 'name', 'category'))
  ->condition('mid', $current_mid, '<>')
  ->addTag('node_access')
  ->execute();
  return $query;
}

 function random_entities() {
 	$data = array();
 	$entities = query_entities();
 	foreach($entities as $entity) {
		$data[] = $entity->mid;
	}

 	$result = array();
	$ready = false;
	$rand = 0;
	$prev = 0;
	$entity_num = count($data) - 1;

	while($ready == false) {
		if(count($result) == 3) {
			$ready = true;
			break;
		}
		else {
			$rand = rand(0, $entity_num);
			$value = $data[$rand];
			if(array_search($value, $result) === false) {
				$result[] = $value;
			}
		}
	}
	return $result;
 } 


/**
* Implements hook_block_info().
*/
function related_block_info() {
  $blocks = array();

  $blocks['related'] = array(
    'info' => t('Bloque para contenido relacionado'),
  );

  return $blocks;
}

function related_block_view($delta = '') {
  $block = array(
    'subject' => '',
    'content' => '',
  );

  if ($delta == 'related') {
    $block['subject'] = t('Contenido Relacionado');

    if (user_access('access content')) {
    	$entities = random_entities();

    	foreach($entities as $entity) {
    	  $values = entity_load('micro', array($entity['mid']));

    	  foreach($values as $value) {
	      	$items[] = array(
    				'data' => array(
      					'#node' => $value,
      					'#theme' => 'related_block_item',
      			),
  			 );
	      }
      }
        
      if (!empty($items)) {
			 $block['content'] = $items;
		  }
    }
  }
  return $block;
}

/**
* Implements hook_theme().
*/
function related_theme($existing, $type, $theme, $path) {
	return array(
		'related_block_item' => array(
			'variables' => array(
				'node' => NULL,
			),
			'template' => 'related-block-item',
		),
	);
}

/**
* Preprocesses related block item.
*/
function template_preprocess_related_block_item(&$variables) {
	$node = $variables['node'];

  global $language;
  $langcode = $language->language;

  // Image
	$img = field_get_items('micro', $node, 'field_res_img');
  $img = field_view_value('micro', $node, 'field_res_img', $img[0]);
  // modify width and height
  $img['#image_style'] = 'recomendado';
  $img['#item']['width'] = '';
  $img['#item']['height'] = '';


  // Title
  $title = field_get_items('micro', $node, 'field_res_title');
  $title = field_view_value('micro', $node, 'field_res_title', $title[0]);

  // Description
  $description = field_get_items('micro', $node, 'field_res_description');
  $description = field_view_value('micro', $node, 'field_res_description', $description[0]);

	$variables['mid'] = $node->mid;
	$variables['img'] = $img;
	$variables['title'] = $title;
	$variables['description'] = $description;
  $variables['langcode'] = $langcode;

}